platform :ios, '16.0'

target 'WhatToWear' do
  use_frameworks!

  pod 'SnapKit', '~> 5.7'
  pod 'Alamofire', '~> 5.9'
  pod 'Kingfisher', '~> 7.11'
  pod 'lottie-ios', '~> 4.4'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end
